import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Pricingcards from '@/components/pricingcards'

export default function Pricing() {
  return (
    <>
      <Head>
        <title>Promotee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-200 dark:bg-gray-900">
       <Navbar/>
       <Pricingcards/>
        <Footer/>
      </main>
    </>
  )
}
